baseurl: "https://pureblueessentials.netlify.app"
# override .Site.Title for copyright notice
# copyright: "Custom Business Name"
# canonifyURLs: false
# disableAliases: true
# disableHugoGeneratorInject: true
# disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
# googleAnalytics: 
# for xml output
languageCode: "en-au"
# for website
defaultContentLanguage: "en-au"
languages:
  en-au:
    weight: 1
#pagination 
paginate: 6
rssLimit: 10
title: Pure Blue Essentials

#summary length
summaryLength: 15

# add redirects/headers (netlify)
outputs:
  home: ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
mediaTypes:
  text/netlify:
    suffixes: [""]
    delimiter: ""


outputFormats:
  # add output format for netlify _redirects  
  REDIRECTS:
    mediatype: "text/netlify"
    baseName: "_redirects"
    isPlainText: true
    notAlternative: true
  # add output format for netlify _headers
  HEADERS:
    mediatype: "text/netlify"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

caches:
    getjson:
      dir: ":cacheDir/:project"
      maxAge: "10s"

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

taxonomies:
  category: "categories"

permalinks:
  blog: "/:title/"
  # categories: "/shop/:section/:title"
  shop: "/shop/:slug"
  #categories: "/shop/:section/:slug"
  categories: "/shop/:slug"


# remove white space from minified HTML
minify:
  tdewolff:
    html:
      keepWhitespace: false

# related items widget config
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: "categories"
    weight: 100
  - name: "date"
    weight: 10

# import modules
module:
  imports:
  - path: github.com/future-wd/hugo-image/v2
  - path: github.com/future-wd/hugo-svg-font/v2
  - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
  - path: github.com/future-wd/hugo-snipcart/v3
  - path: github.com/future-wd/hugo-contact-form-xhr/v2