imports:
- path: github.com/future-wd/hugo-responsive-images
- path: github.com/future-wd/hugo-svg-font/v2
- path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
- path: github.com/future-wd/hugo-snipcart/v3
- path: github.com/future-wd/hugo-contact-form-xhr/v2
