## Page Title
titleSeparator: "-"
# only used on home page
# titleAddition: "hand made from pure ingredients found in nature."
titleAddition: All Natural Ingredients
# fall back description if a page does not have a description.
description: "Providing the essentials to optimise your health, hand made from pure ingredients found in nature."


# Images
quality: 85
bgColor: "#fff"
landscapePhotoWidths: [900, 800, 700, 600, 500]
portraitPhotoWidths: [800, 700, 600, 500]
lqipWidth: "20x"
smallLimit: "300"

# Footer - override default copyright message
# footer: "Custom Footer Text"

# Alert
alert: true
alertText: Free shipping within Australia for orders over $120 | [15% off for XMAS use code **G1QB422Y**]({{< relref "/news" >}})






snipcart:
  enabled: true # defaults to true
  # key: NGUxMjlkZjUtNjAxNC00OGY3LWJjNWItOTRjMzkzZTk2NzU1NjM3Nzg4MDk4NTI5MjU1Njk5 # test
  key: MmY2YTFkN2MtMmQyNS00ZGE4LWIxNjMtODc5MDRiNGJmZTJlNjM3Nzg4MDk4NTI5MjU1Njk5

  side: false # or false for full screen cart
  bootstrap: true # enables snipcart z-index css for bootstrap compatibility


